import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.features": "Fonctionnalités",
    "nav.pricing": "Tarifs",
    "nav.dashboard": "Dashboard",
    "nav.start": "Commencer",
    
    // Hero
    "hero.badge": "IA de dernière génération",
    "hero.title1": "Transformez vos",
    "hero.title2": "vidéos longues",
    "hero.title3": "en clips viraux",
    "hero.description": "L'IA qui analyse vos VOD Twitch et podcasts YouTube pour créer automatiquement des clips courts optimisés pour TikTok et Shorts.",
    "hero.cta.start": "Commencer gratuitement",
    "hero.cta.demo": "Voir la démo",
    "hero.stats.clips": "Clips générés",
    "hero.stats.creators": "Créateurs actifs",
    "hero.badge.live": "IA en action",
    
    // Features
    "features.badge": "Fonctionnalités IA",
    "features.title1": "Tout ce dont vous avez besoin pour",
    "features.title2": "créer du contenu viral",
    "features.description": "Des outils puissants alimentés par l'IA pour transformer vos longues vidéos en contenus courts et engageants en quelques clics.",
    "features.premium": "Premium",
    "features.ai.title": "Détection IA d'événements",
    "features.ai.desc": "L'IA analyse l'audio et détecte automatiquement les moments forts : rires, cris, pics d'émotion et changements de sujet.",
    "features.keywords.title": "Ciblage par mots-clés",
    "features.keywords.desc": "Définissez vos mots-clés spécifiques et l'IA ne découpe que les moments où ils sont prononcés. Parfait pour le contenu thématique.",
    "features.crop.title": "Recadrage intelligent 9:16",
    "features.crop.desc": "Formatage automatique vertical avec suivi des locuteurs. Vos clips sont prêts pour TikTok et Shorts immédiatement.",
    "features.subtitles.title": "Sous-titres dynamiques",
    "features.subtitles.desc": "Génération automatique de sous-titres français avec animations et surlignage du mot actuel. Styles premium disponibles.",
    "features.translate.title": "Traduction multilingue",
    "features.translate.desc": "Traduisez vos clips dans plusieurs langues avec génération automatique des sous-titres traduits. Élargissez votre audience.",
    "features.export.title": "Export professionnel",
    "features.export.desc": "Exportation HD et 4K, fichiers SRT séparés, suppression du filigrane. Qualité broadcast pour vos clips.",
    "features.autopublish.title": "Publication Automatique Multi-Plateformes",
    "features.autopublish.desc": "Connexion API TikTok, YouTube et Instagram. L'IA publie automatiquement vos clips aux horaires optimaux avec titres, descriptions et hashtags générés. Planification intelligente pour maximiser la portée.",
    "features.music.title": "Suggestion de Musique Virale",
    "features.music.desc": "L'IA analyse le sujet du clip et suggère une musique ou un son tendance sur TikTok/Reels correspondant au rythme. Synchronisation automatique de l'audio.",
    "features.editor.title": "Éditeur Visuel Rapide ⚡",
    "features.editor.desc": "Notre avantage compétitif majeur : éditez vos clips en quelques clics sans logiciel lourd. Ajoutez titres, filtres, transitions, calques personnalisés. Interface intuitive niveau CapCut, directement dans votre navigateur.",
    
    // Demo
    "demo.badge": "Essayez-le",
    "demo.title1": "Voyez l'IA",
    "demo.title2": "en Action",
    "demo.description": "Découvrez comment MonShort transforme instantanément vos vidéos en clips courts optimisés pour les réseaux sociaux.",
    "demo.feature1": "Analyse IA",
    "demo.feature2": "Découpage Auto",
    "demo.feature3": "Format 9:16",
    
    // Chatbot
    "chatbot.open": "Ouvrir le chat",
    "chatbot.title": "MonAide",
    "chatbot.subtitle": "Assistant virtuel IA",
    "chatbot.welcome": "Bonjour ! Comment puis-je vous aider avec MonShort aujourd'hui ?",
    "chatbot.placeholder": "Posez votre question...",
    "chatbot.error": "Désolé, une erreur s'est produite. Veuillez réessayer.",
    
    // Pricing
    "pricing.badge": "Tarifs transparents",
    "pricing.title": "Choisissez votre",
    "pricing.title2": "plan",
    "pricing.description": "Commencez gratuitement et évoluez selon vos besoins. Aucun engagement, annulez à tout moment.",
    "pricing.popular": "Plus populaire",
    "pricing.free.name": "Gratuit",
    "pricing.free.desc": "Parfait pour découvrir l'IA",
    "pricing.free.f1": "5 clips par mois",
    "pricing.free.f2": "Détection IA d'événements",
    "pricing.free.f3": "Format vertical 9:16",
    "pricing.free.f4": "Sous-titres dynamiques",
    "pricing.free.f5": "Export HD avec filigrane",
    "pricing.free.f6": "Communauté Discord",
    "pricing.free.cta": "Commencer gratuitement",
    "pricing.pro.name": "Pro",
    "pricing.pro.desc": "Automatisation complète de la chaîne de publication",
    "pricing.pro.f1": "Clips illimités",
    "pricing.pro.f2": "Ciblage par mots-clés",
    "pricing.pro.f3": "Traduction multilingue",
    "pricing.pro.f4": "Styles de sous-titres avancés",
    "pricing.pro.f5": "Export 4K sans filigrane",
    "pricing.pro.f6": "Publication automatique TikTok, YouTube, Instagram (Connexion API)",
    "pricing.pro.f7": "Suggestion de musique virale",
    "pricing.pro.f8": "Éditeur visuel rapide niveau CapCut",
    "pricing.pro.f9": "Logo/Branding personnalisé",
    "pricing.pro.f10": "Support prioritaire",
    "pricing.pro.cta": "Essayer Pro",
    "pricing.agency.name": "Agence",
    "pricing.agency.desc": "Pour les équipes et agences",
    "pricing.agency.f1": "Tout de Pro +",
    "pricing.agency.f2": "Publication Automatique Multi-Comptes",
    "pricing.agency.f3": "5 comptes utilisateurs",
    "pricing.agency.f4": "Recadrage multi-sources",
    "pricing.agency.f5": "API privée",
    "pricing.agency.f6": "Formation personnalisée",
    "pricing.agency.f7": "Gestionnaire de compte dédié",
    "pricing.agency.cta": "Contacter les ventes",
    
    // Footer
    "footer.rights": "Tous droits réservés.",
    "footer.powered": "Propulsé par l'IA de dernière génération",
    
    // Dashboard
    "dashboard.welcome": "Bienvenue sur",
    "dashboard.subtitle": "Téléchargez votre vidéo ou collez une URL pour commencer",
    "dashboard.upload.title": "Télécharger un fichier",
    "dashboard.upload.desc": "Glissez-déposez votre vidéo ou cliquez pour parcourir",
    "dashboard.upload.button": "Parcourir les fichiers",
    "dashboard.upload.format": "MP4, MOV, AVI • Max 2GB",
    "dashboard.url.title": "Importer depuis une URL",
    "dashboard.url.desc": "Collez un lien Twitch VOD ou YouTube",
    "dashboard.url.placeholder": "https://twitch.tv/videos/...",
    "dashboard.url.button": "Analyser avec l'IA",
    "dashboard.recent": "Clips récents",
    "dashboard.viewAll": "Voir tout",
    "dashboard.untitled": "Clip sans titre",
    "dashboard.ago": "Il y a",
    "dashboard.day": "jour",
    "dashboard.days": "jours",
    
    // Editor
    "editor.back": "Retour",
    "editor.reset": "Réinitialiser",
    "editor.save": "Sauvegarder",
    "editor.viral": "IA Viral",
    "editor.effects": "Effets",
    "editor.text": "Texte",
    "editor.export": "Export",
    "editor.noVideo": "Aucune vidéo chargée",
    "editor.quickActions": "Actions rapides",
    "editor.aiSuggestions": "Suggestions IA",
    "editor.tips": "Conseils",
    "editor.tip1": "Utilisez les filtres pour un style unique",
    "editor.tip2": "Ajoutez du texte pour plus d'impact",
    "editor.tip3": "L'IA suggère les meilleurs hashtags",
    "editor.presetFilters": "Filtres prédéfinis",
    "editor.adjustments": "Ajustements manuels",
    "editor.brightness": "Luminosité",
    "editor.contrast": "Contraste",
    "editor.saturation": "Saturation",
    "editor.blur": "Flou",
    "editor.filter.none": "Aucun",
    "editor.filter.vintage": "Vintage",
    "editor.filter.cool": "Froid",
    "editor.filter.warm": "Chaud",
    "editor.filter.dramatic": "Dramatique",
    "editor.addText": "Ajouter du texte",
    "editor.textPlaceholder": "Votre texte ici...",
    "editor.addTextButton": "Ajouter",
    "editor.activeTexts": "Textes actifs",
    "editor.animation.none": "Aucune",
    "editor.animation.fadeIn": "Apparition",
    "editor.animation.slideUp": "Montée",
    "editor.animation.bounce": "Rebond",
    "editor.textAdded": "Texte ajouté !",
    "editor.aiSuggestionsTitle": "Suggestions virales IA",
    "editor.generateSuggestions": "Générer des suggestions",
    "editor.generating": "Génération...",
    "editor.suggestedTitle": "Titre suggéré",
    "editor.suggestedHashtags": "Hashtags suggérés",
    "editor.suggestedDescription": "Description suggérée",
    "editor.copied": "Copié !",
    "editor.exportOptions": "Options d'export",
    "editor.exportNote": "Format 9:16 optimisé pour TikTok/Shorts/Reels",
    "editor.errorNoVideo": "Aucune vidéo chargée",
    "editor.errorGenerating": "Erreur lors de la génération",
    "editor.suggestionsGenerated": "Suggestions générées !",
    "editor.exportStarted": "Export démarré...",
    "editor.targetLanguage": "Langue de traduction",
    "editor.viralityScore": "Score de Viralité",
    "editor.analyzing": "Analyse...",
    "editor.analyzeVirality": "Analyser la viralité",
    "editor.viralityAnalyzed": "Analyse terminée",
    "editor.viralityError": "Erreur lors de l'analyse",
    "editor.strengths": "Points forts",
    "editor.weaknesses": "Points faibles",
    "editor.scoreSuggestions": "Suggestions d'amélioration",
    "editor.dynamicThumbnail": "Miniature Dynamique",
    "editor.generateThumbnail": "Générer une miniature",
    "editor.thumbnailGenerated": "Miniature générée",
    "editor.thumbnailError": "Erreur lors de la génération",
    "editor.thumbnailDownloaded": "Miniature téléchargée",
    "editor.downloadThumbnail": "Télécharger la miniature",
    "editor.formatConversion": "Déclinaison de Format",
    "editor.formatHint": "Sélectionnez les formats pour lesquels exporter votre vidéo",
    "editor.exportHD": "Exporter en HD",
    "editor.export4K": "Exporter en 4K",
    
    // Speed Control
    "editor.speedControl": "Contrôle de Vitesse",
    "editor.speed": "Vitesse",
    "editor.startTime": "Début",
    "editor.endTime": "Fin",
    "editor.applySpeed": "Appliquer Vitesse",
    "editor.appliedEffects": "Effets Appliqués",
    
    // Layer Manager
    "editor.layers": "Calques",
    "editor.noLayers": "Aucun calque ajouté",
    "editor.opacity": "Opacité",
    
    // Title Templates
    "editor.titleTemplates": "Modèles de Titre",
    "editor.titleText": "Texte du Titre",
    "editor.enterTitle": "Entrez votre titre...",
    "editor.selectTemplateAndText": "Sélectionnez un modèle et entrez du texte",
    "editor.templateApplied": "Modèle appliqué !",
    "editor.templateDetails": "Détails du Modèle",
    "editor.animation": "Animation",
    "editor.fontSize": "Taille Police",
    "editor.color": "Couleur",
    
    // Schedule Panel
    "editor.schedulePublication": "Planifier la Publication",
    "editor.scheduleDescription": "Planifiez vos clips pour une publication automatique sur vos réseaux sociaux",
    "editor.selectPlatforms": "Sélectionner les Plateformes",
    "editor.optimalTime": "Heure Optimale",
    "editor.selectDate": "Date",
    "editor.pickDate": "Choisir une date",
    "editor.selectTime": "Heure",
    "editor.schedulePost": "Planifier",
    "editor.selectDateAndPlatform": "Sélectionnez une date et au moins une plateforme",
    "editor.postScheduled": "Publication planifiée !",
    "editor.scheduledPosts": "Publications Planifiées",
    "editor.proTip": "Conseil Pro",
    "editor.scheduleTip": "Publiez aux heures de pointe pour maximiser votre portée. L'IA suggère les meilleurs créneaux.",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.features": "Features",
    "nav.pricing": "Pricing",
    "nav.dashboard": "Dashboard",
    "nav.start": "Get Started",
    
    // Hero
    "hero.badge": "Next-gen AI",
    "hero.title1": "Transform your",
    "hero.title2": "long videos",
    "hero.title3": "into viral clips",
    "hero.description": "The AI that analyzes your Twitch VODs and YouTube podcasts to automatically create short clips optimized for TikTok and Shorts.",
    "hero.cta.start": "Start for free",
    "hero.cta.demo": "Watch demo",
    "hero.stats.clips": "Clips generated",
    "hero.stats.creators": "Active creators",
    "hero.badge.live": "AI in action",
    
    // Features
    "features.badge": "AI Features",
    "features.title1": "Everything you need to",
    "features.title2": "create viral content",
    "features.description": "Powerful AI-driven tools to transform your long videos into short, engaging content in just a few clicks.",
    "features.premium": "Premium",
    "features.ai.title": "AI Event Detection",
    "features.ai.desc": "AI analyzes audio and automatically detects highlights: laughter, screams, emotion peaks and topic changes.",
    "features.keywords.title": "Keyword Targeting",
    "features.keywords.desc": "Define your specific keywords and AI will only cut moments where they're mentioned. Perfect for thematic content.",
    "features.crop.title": "Smart 9:16 Cropping",
    "features.crop.desc": "Automatic vertical formatting with speaker tracking. Your clips are ready for TikTok and Shorts immediately.",
    "features.subtitles.title": "Dynamic Subtitles",
    "features.subtitles.desc": "Automatic French subtitle generation with animations and current word highlighting. Premium styles available.",
    "features.translate.title": "Multilingual Translation",
    "features.translate.desc": "Translate your clips into multiple languages with automatic translated subtitle generation. Expand your audience.",
    "features.export.title": "Professional Export",
    "features.export.desc": "HD and 4K export, separate SRT files, watermark removal. Broadcast quality for your clips.",
    "features.autopublish.title": "Multi-Platform Auto-Publishing",
    "features.autopublish.desc": "TikTok, YouTube and Instagram API connections. AI automatically publishes your clips at optimal times with generated titles, descriptions and hashtags. Smart scheduling to maximize reach.",
    "features.music.title": "Viral Music Suggestion",
    "features.music.desc": "AI analyzes your clip's topic and suggests trending music or sounds from TikTok/Reels that match the rhythm. Automatic audio synchronization included.",
    "features.editor.title": "Quick Visual Editor ⚡",
    "features.editor.desc": "Our major competitive advantage: edit your clips in seconds without heavy software. Add titles, filters, transitions, custom layers. CapCut-level intuitive interface, directly in your browser.",
    
    // Demo
    "demo.badge": "Try It Live",
    "demo.title1": "See the AI",
    "demo.title2": "in Action",
    "demo.description": "Discover how MonShort instantly transforms your videos into short clips optimized for social media.",
    "demo.feature1": "AI Analysis",
    "demo.feature2": "Auto-Cutting",
    "demo.feature3": "9:16 Format",
    
    // Chatbot
    "chatbot.open": "Open chat",
    "chatbot.title": "MonAide",
    "chatbot.subtitle": "AI Virtual Assistant",
    "chatbot.welcome": "Hello! How can I help you with MonShort today?",
    "chatbot.placeholder": "Ask your question...",
    "chatbot.error": "Sorry, an error occurred. Please try again.",
    
    // Pricing
    "pricing.badge": "Transparent pricing",
    "pricing.title": "Choose your",
    "pricing.title2": "plan",
    "pricing.description": "Start for free and scale as you grow. No commitment, cancel anytime.",
    "pricing.popular": "Most popular",
    "pricing.free.name": "Free",
    "pricing.free.desc": "Perfect to discover AI",
    "pricing.free.f1": "5 clips per month",
    "pricing.free.f2": "AI event detection",
    "pricing.free.f3": "9:16 vertical format",
    "pricing.free.f4": "Dynamic subtitles",
    "pricing.free.f5": "HD export with watermark",
    "pricing.free.f6": "Discord community",
    "pricing.free.cta": "Start for free",
    "pricing.pro.name": "Pro",
    "pricing.pro.desc": "Complete publishing automation",
    "pricing.pro.f1": "Unlimited clips",
    "pricing.pro.f2": "Keyword targeting",
    "pricing.pro.f3": "Multilingual translation",
    "pricing.pro.f4": "Advanced subtitle styles",
    "pricing.pro.f5": "4K export without watermark",
    "pricing.pro.f6": "Auto-publish to TikTok, YouTube, Instagram (API Connection)",
    "pricing.pro.f7": "Viral music suggestion",
    "pricing.pro.f8": "CapCut-level quick visual editor",
    "pricing.pro.f9": "Custom logo/branding",
    "pricing.pro.f10": "Priority support",
    "pricing.pro.cta": "Try Pro",
    "pricing.agency.name": "Agency",
    "pricing.agency.desc": "For teams and agencies",
    "pricing.agency.f1": "Everything in Pro +",
    "pricing.agency.f2": "Advanced Multi-Account Auto-Publishing",
    "pricing.agency.f3": "5 user accounts",
    "pricing.agency.f4": "Multi-source cropping",
    "pricing.agency.f5": "Private API",
    "pricing.agency.f6": "Custom training",
    "pricing.agency.f7": "Dedicated account manager",
    "pricing.agency.cta": "Contact sales",
    
    // Footer
    "footer.rights": "All rights reserved.",
    "footer.powered": "Powered by next-gen AI",
    
    // Dashboard
    "dashboard.welcome": "Welcome to",
    "dashboard.subtitle": "Upload your video or paste a URL to get started",
    "dashboard.upload.title": "Upload a file",
    "dashboard.upload.desc": "Drag and drop your video or click to browse",
    "dashboard.upload.button": "Browse files",
    "dashboard.upload.format": "MP4, MOV, AVI • Max 2GB",
    "dashboard.url.title": "Import from URL",
    "dashboard.url.desc": "Paste a Twitch VOD or YouTube link",
    "dashboard.url.placeholder": "https://twitch.tv/videos/...",
    "dashboard.url.button": "Analyze with AI",
    "dashboard.recent": "Recent clips",
    "dashboard.viewAll": "View all",
    "dashboard.untitled": "Untitled clip",
    "dashboard.ago": "",
    "dashboard.day": "day ago",
    "dashboard.days": "days ago",
    
    // Editor
    "editor.back": "Back",
    "editor.reset": "Reset",
    "editor.save": "Save",
    "editor.viral": "AI Viral",
    "editor.effects": "Effects",
    "editor.text": "Text",
    "editor.export": "Export",
    "editor.noVideo": "No video loaded",
    "editor.quickActions": "Quick Actions",
    "editor.aiSuggestions": "AI Suggestions",
    "editor.tips": "Tips",
    "editor.tip1": "Use filters for unique style",
    "editor.tip2": "Add text for more impact",
    "editor.tip3": "AI suggests best hashtags",
    "editor.presetFilters": "Preset Filters",
    "editor.adjustments": "Manual Adjustments",
    "editor.brightness": "Brightness",
    "editor.contrast": "Contrast",
    "editor.saturation": "Saturation",
    "editor.blur": "Blur",
    "editor.filter.none": "None",
    "editor.filter.vintage": "Vintage",
    "editor.filter.cool": "Cool",
    "editor.filter.warm": "Warm",
    "editor.filter.dramatic": "Dramatic",
    "editor.addText": "Add Text",
    "editor.textPlaceholder": "Your text here...",
    "editor.addTextButton": "Add",
    "editor.activeTexts": "Active Texts",
    "editor.animation.none": "None",
    "editor.animation.fadeIn": "Fade In",
    "editor.animation.slideUp": "Slide Up",
    "editor.animation.bounce": "Bounce",
    "editor.textAdded": "Text added!",
    "editor.aiSuggestionsTitle": "Viral AI Suggestions",
    "editor.generateSuggestions": "Generate Suggestions",
    "editor.generating": "Generating...",
    "editor.suggestedTitle": "Suggested Title",
    "editor.suggestedHashtags": "Suggested Hashtags",
    "editor.suggestedDescription": "Suggested Description",
    "editor.copied": "Copied!",
    "editor.exportOptions": "Export Options",
    "editor.exportNote": "9:16 format optimized for TikTok/Shorts/Reels",
    "editor.errorNoVideo": "No video loaded",
    "editor.errorGenerating": "Error generating suggestions",
    "editor.suggestionsGenerated": "Suggestions generated!",
    "editor.exportStarted": "Export started...",
    "editor.targetLanguage": "Translation Language",
    "editor.viralityScore": "Virality Score",
    "editor.analyzing": "Analyzing...",
    "editor.analyzeVirality": "Analyze Virality",
    "editor.viralityAnalyzed": "Analysis complete",
    "editor.viralityError": "Analysis error",
    "editor.strengths": "Strengths",
    "editor.weaknesses": "Weaknesses",
    "editor.scoreSuggestions": "Improvement Suggestions",
    "editor.dynamicThumbnail": "Dynamic Thumbnail",
    "editor.generateThumbnail": "Generate Thumbnail",
    "editor.thumbnailGenerated": "Thumbnail generated",
    "editor.thumbnailError": "Generation error",
    "editor.thumbnailDownloaded": "Thumbnail downloaded",
    "editor.downloadThumbnail": "Download Thumbnail",
    "editor.formatConversion": "Format Conversion",
    "editor.formatHint": "Select formats to export your video",
    "editor.exportHD": "Export in HD",
    "editor.export4K": "Export in 4K",
    
    // Speed Control
    "editor.speedControl": "Speed Control",
    "editor.speed": "Speed",
    "editor.startTime": "Start",
    "editor.endTime": "End",
    "editor.applySpeed": "Apply Speed",
    "editor.appliedEffects": "Applied Effects",
    
    // Layer Manager
    "editor.layers": "Layers",
    "editor.noLayers": "No layers added",
    "editor.opacity": "Opacity",
    
    // Title Templates
    "editor.titleTemplates": "Title Templates",
    "editor.titleText": "Title Text",
    "editor.enterTitle": "Enter your title...",
    "editor.selectTemplateAndText": "Select a template and enter text",
    "editor.templateApplied": "Template applied!",
    "editor.templateDetails": "Template Details",
    "editor.animation": "Animation",
    "editor.fontSize": "Font Size",
    "editor.color": "Color",
    
    // Schedule Panel
    "editor.schedulePublication": "Schedule Publication",
    "editor.scheduleDescription": "Schedule your clips for automatic publishing on your social networks",
    "editor.selectPlatforms": "Select Platforms",
    "editor.optimalTime": "Optimal Time",
    "editor.selectDate": "Date",
    "editor.pickDate": "Pick a date",
    "editor.selectTime": "Time",
    "editor.schedulePost": "Schedule",
    "editor.selectDateAndPlatform": "Select a date and at least one platform",
    "editor.postScheduled": "Post scheduled!",
    "editor.scheduledPosts": "Scheduled Posts",
    "editor.proTip": "Pro Tip",
    "editor.scheduleTip": "Post at peak times to maximize your reach. AI suggests the best slots.",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("fr");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
